fix negative relative mouse moves
fixes this error:

```
Internal_error: {"message":"failed during drag movement: mousemove_relative: unrecognized option '-60'\nUsage:
  mousemove_relative [options] \u003cx\u003e \u003cy\u003e\n-c, --clearmodifiers - reset active modifiers (alt, etc)
  while typing\n-p, --polar - Use polar coordinates. X as an angle, Y as distance\n--sync - only exit once the mouse
  has moved\n\nUsing polar coordinate mode makes 'x' the angle (in degrees) and\n'y' the distance.\n\nIf you want to
  use negative numbers for a coordinate, you'll need to\ninvoke it this way (with the '--'):\n mousemove_relative -- -
  20 -15\notherwise, normal usage looks like this:\n mousemove_relative 100 140\n"} .
```

tested manually:  https://screen.studio/share/lM76bBHd